version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: btg_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: btg_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - btg_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${DOCKERHUB_USER:-ismaeltrochas}/btg-technical-test:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btg_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/btg_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: cGFzc3dvcmRTZWNyZXRLZXlCVEdUZXN0MjAyNlZlcnlMb25nU2VjcmV0S2V5Rm9ySldU
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  btg_postgres_data:

