
CREATE TABLE clientes (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL UNIQUE,
    apellidos   VARCHAR(100) NOT NULL,
    ciudad      VARCHAR(100) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'ROLE_CLIENTE',
    saldo       DOUBLE PRECISION NOT NULL DEFAULT 500000
);

CREATE TABLE fondos (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(150) NOT NULL,
    monto_minimo  DOUBLE PRECISION NOT NULL,
    moneda        VARCHAR(10)  NOT NULL,
    categoria     VARCHAR(100) NOT NULL
);

CREATE TABLE suscripciones (
    id          BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  BIGINT           NOT NULL REFERENCES clientes(id),
    fondo_id    BIGINT           NOT NULL REFERENCES fondos(id),
    monto       DOUBLE PRECISION NOT NULL,
    activo      BOOLEAN          NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX idx_suscripcion_activa
    ON suscripciones (cliente_id, fondo_id) WHERE activo = TRUE;

CREATE INDEX idx_suscripciones_cliente_activo
    ON suscripciones (cliente_id, activo);

CREATE TABLE transacciones (
    id          UUID             PRIMARY KEY,
    cliente_id  BIGINT           NOT NULL REFERENCES clientes(id),
    fondo_id    BIGINT           NOT NULL REFERENCES fondos(id),
    tipo        VARCHAR(20)      NOT NULL,
    monto       DOUBLE PRECISION NOT NULL,
    fecha       TIMESTAMP        NOT NULL DEFAULT NOW()
);

